"""
Unit tests for validation anomaly identifiers.

File:
    tests/validation/test_anomalies.py

Description:
    Tests the stability, consistency, and classification of anomaly
    identifiers generated by the PCa-tRFQTL validation framework.

    These tests ensure that validation anomalies can be reliably
    identified across validation runs and subsequently tracked in
    validation reports.

Author:
    I Putu Indra Arsana

Project:
    Integrative Analysis of Prostate Cancer Risk Variants,
    tRNA-Derived Fragment QTLs, and Transcript Isoform Regulation

License:
    MIT
"""

from __future__ import annotations

from pcatrfqtl.validation.validators.trfqtl import TRFQTLValidator

def create_validator() -> TRFQTLValidator:
    """
    Create a TRFQTL validator for unit testing.
    """
    return TRFQTLValidator()


# ===========================================================================
# SNP ID anomalies
# ===========================================================================


def test_invalid_snp_id_has_anomaly_id() -> None:
    """
    Invalid SNP identifiers must generate a classified anomaly.
    """

    validator = create_validator()

    result = validator.validate_snp_ids(
        [
            "rs123",
            "INVALID",
        ],
        "SNP ID",
    )

    assert len(result) == 1
    assert "TRFQTL-SNP-001" in result[0]


def test_invalid_snp_id_anomaly_is_stable() -> None:
    """
    The anomaly identifier must remain stable across repeated validation.
    """

    validator = create_validator()

    first = validator.validate_snp_ids(
        ["INVALID"],
        "SNP ID",
    )

    second = validator.validate_snp_ids(
        ["INVALID"],
        "SNP ID",
    )

    assert first == second
    assert "TRFQTL-SNP-001" in first[0]


# ===========================================================================
# Allele anomalies
# ===========================================================================


def test_invalid_allele_has_anomaly_id() -> None:
    """
    Invalid allele representations must generate a classified anomaly.
    """

    validator = create_validator()

    result = validator.validate_alleles(
        [
            "A/T",
            "X/Y",
        ]
    )

    assert len(result) == 1
    assert "TRFQTL-ALLELE-001" in result[0]


def test_invalid_allele_anomaly_is_stable() -> None:
    """
    Allele anomaly identifiers must remain stable.
    """

    validator = create_validator()

    first = validator.validate_alleles(
        ["X/Y"],
    )

    second = validator.validate_alleles(
        ["X/Y"],
    )

    assert first == second
    assert "TRFQTL-ALLELE-001" in first[0]


# ===========================================================================
# Effect allele anomalies
# ===========================================================================


def test_invalid_effect_allele_has_anomaly_id() -> None:
    """
    Invalid effect alleles must generate a classified anomaly.
    """

    validator = create_validator()

    result = validator.validate_effect_alleles(
        [
            "A",
            "X",
        ]
    )

    assert len(result) == 1
    assert "TRFQTL-EFFECT-ALLELE-001" in result[0]


def test_invalid_effect_allele_anomaly_is_stable() -> None:
    """
    Effect-allele anomaly identifiers must remain stable.
    """

    validator = create_validator()

    first = validator.validate_effect_alleles(
        ["X"],
    )

    second = validator.validate_effect_alleles(
        ["X"],
    )

    assert first == second
    assert "TRFQTL-EFFECT-ALLELE-001" in first[0]


# ===========================================================================
# Valid data
# ===========================================================================


def test_valid_snp_ids_generate_no_anomaly() -> None:
    """
    Valid SNP identifiers must not generate anomalies.
    """

    validator = create_validator()

    result = validator.validate_snp_ids(
        [
            "rs123",
            "rs456",
            "rs789",
        ],
        "SNP ID",
    )

    assert result == []


def test_valid_alleles_generate_no_anomaly() -> None:
    """
    Valid allele representations must not generate anomalies.
    """

    validator = create_validator()

    result = validator.validate_alleles(
        [
            "A/T",
            "G/C",
            "C",
            "A",
        ]
    )

    assert result == []


def test_valid_effect_alleles_generate_no_anomaly() -> None:
    """
    Valid effect alleles must not generate anomalies.
    """

    validator = create_validator()

    result = validator.validate_effect_alleles(
        [
            "A",
            "C",
            "G",
            "T",
        ]
    )

    assert result == []


# ===========================================================================
# Multiple anomalies
# ===========================================================================


def test_multiple_invalid_snp_ids_generate_multiple_anomalies() -> None:
    """
    Multiple invalid SNP identifiers must be reported independently.
    """

    validator = create_validator()

    result = validator.validate_snp_ids(
        [
            "INVALID1",
            "rs123",
            "INVALID2",
        ],
        "SNP ID",
    )

    assert len(result) == 2

    assert all(
        "TRFQTL-SNP-001" in message
        for message in result
    )


def test_anomaly_messages_include_invalid_value() -> None:
    """
    Anomaly messages should retain the offending value for traceability.
    """

    validator = create_validator()

    result = validator.validate_snp_ids(
        ["INVALID"],
        "SNP ID",
    )

    assert len(result) == 1
    assert "INVALID" in result[0]


# ===========================================================================
# Known dataset anomaly
# ===========================================================================


def test_s10_invalid_snp_id_is_classified_consistently() -> None:
    """
    The known S10 anomaly where SNP ID '6' appears instead of an rsID
    must use the same SNP anomaly classification as other invalid SNP IDs.

    This test documents the observed source-data anomaly without
    modifying or silently correcting the original dataset.
    """

    validator = create_validator()

    result = validator.validate_snp_ids(
        ["6"],
        "SNP ID",
    )

    assert len(result) == 1
    assert "TRFQTL-SNP-001" in result[0]
    assert "6" in result[0]