"""
PCa-tRFQTL Research Pipeline
=============================

File:
    src/pcatrfqtl/analysis/m5/gwas_cross_study_signal.py

Description:
    M5.3C.3E cross-study synthesis utilities for prostate cancer GWAS
    regional disease signals.

    This module integrates standardized locus-level GWAS evidence across
    studies for each candidate tRF-QTL lead.

    The stage evaluates:
        - direct candidate-lead association;
        - strongest regional association;
        - distance between the regional top signal and candidate lead;
        - regional significance burden;
        - recurrence of associated variants across studies;
        - cross-study disease-signal consistency;
        - descriptive candidate-locus ranking.

    Important scientific safeguards:
        - No LD inference is performed.
        - Physical distance is not interpreted as LD.
        - No colocalization is performed.
        - No fine-mapping is performed.
        - No causal inference is performed.
        - Study recurrence is not interpreted as independent replication
          unless study provenance establishes independence.
        - Candidate ranking is descriptive and does not imply causality.

Author:
    I Putu Indra Arsana

Project:
    Integrative Analysis of Prostate Cancer Risk Variants,
    tRNA-Derived Fragment QTLs, and Transcript Isoform Regulation

License:
    MIT
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

import numpy as np
import pandas as pd


GENOME_WIDE_SIGNIFICANCE = 5e-8

SUGGESTIVE_SIGNIFICANCE = 1e-5


# ============================================================================
# Models
# ============================================================================


@dataclass(frozen=True)
class CrossStudySynthesisResult:
    """Outputs generated by cross-study disease-signal synthesis."""

    locus_evidence: pd.DataFrame

    lead_synthesis: pd.DataFrame

    variant_recurrence: pd.DataFrame


# ============================================================================
# Scalar helpers
# ============================================================================


def _float_or_none(
    value: Any,
) -> float | None:
    """Return finite float or None."""

    if pd.isna(
        value
    ):
        return None

    value = float(
        value
    )

    if not np.isfinite(
        value
    ):
        return None

    return value


def _int_or_none(
    value: Any,
) -> int | None:
    """Return integer or None."""

    if pd.isna(
        value
    ):
        return None

    return int(
        value
    )


def _safe_neg_log10(
    p_value: Any,
) -> float | None:
    """Calculate -log10(p) safely."""

    value = _float_or_none(
        p_value
    )

    if value is None:
        return None

    if value <= 0:
        return None

    return float(
        -np.log10(
            value
        )
    )


# ============================================================================
# Per-locus evidence
# ============================================================================


def build_locus_evidence(
    disease_signal: pd.DataFrame,
) -> pd.DataFrame:
    """
    Build one standardized evidence record per study × candidate lead.

    The source is the M5.3C.3D disease-signal summary.
    """

    required = {
        "study_accession",
        "lead_rsid",
        "variant_rows",
        "lead_present",
        "lead_p_value",
        "lead_beta",
        "lead_standard_error",
        "lead_effect_allele_frequency",
        "minimum_p_value",
        "top_variant_rsid",
        "top_variant_id",
        "top_variant_position",
        "top_variant_distance_to_lead",
        "top_variant_effect_allele",
        "top_variant_other_allele",
        "top_variant_beta",
        "top_variant_standard_error",
        "top_variant_eaf",
        "genome_wide_significant_variants",
        "suggestive_significant_variants",
        "suggestive_only_variants",
        "has_genome_wide_signal",
        "has_suggestive_signal",
    }

    missing = (
        required
        - set(
            disease_signal.columns
        )
    )

    if missing:

        raise ValueError(
            "Disease-signal summary is missing required columns: "
            f"{sorted(missing)}"
        )

    out = disease_signal.copy()

    # ------------------------------------------------------------------
    # Association strength
    # ------------------------------------------------------------------

    out[
        "regional_neg_log10_p"
    ] = out[
        "minimum_p_value"
    ].map(
        _safe_neg_log10
    )

    out[
        "lead_neg_log10_p"
    ] = out[
        "lead_p_value"
    ].map(
        _safe_neg_log10
    )

    # ------------------------------------------------------------------
    # Lead versus regional signal
    # ------------------------------------------------------------------

    out[
        "regional_signal_stronger_than_lead"
    ] = (
        out[
            "minimum_p_value"
        ].notna()
        &
        (
            out[
                "lead_p_value"
            ].isna()
            |
            (
                out[
                    "minimum_p_value"
                ]
                <
                out[
                    "lead_p_value"
                ]
            )
        )
    )

    # Ratio used descriptively only.
    #
    # Values >> 1 indicate that the regional top signal has a substantially
    # smaller p-value than the candidate lead itself.
    valid_ratio = (
        out[
            "minimum_p_value"
        ].notna()
        &
        out[
            "lead_p_value"
        ].notna()
        &
        out[
            "minimum_p_value"
        ].gt(
            0
        )
        &
        out[
            "lead_p_value"
        ].gt(
            0
        )
    )

    out[
        "lead_to_regional_p_ratio"
    ] = np.nan

    out.loc[
        valid_ratio,
        "lead_to_regional_p_ratio",
    ] = (
        out.loc[
            valid_ratio,
            "lead_p_value",
        ]
        /
        out.loc[
            valid_ratio,
            "minimum_p_value",
        ]
    )

    # ------------------------------------------------------------------
    # Distance
    # ------------------------------------------------------------------

    out[
        "top_variant_absolute_distance_to_lead"
    ] = (
        pd.to_numeric(
            out[
                "top_variant_distance_to_lead"
            ],
            errors="coerce",
        )
        .abs()
        .astype(
            "Int64"
        )
    )

    # ------------------------------------------------------------------
    # Descriptive signal class
    # ------------------------------------------------------------------

    out[
        "regional_signal_class"
    ] = "NO_SUGGESTIVE_SIGNAL"

    out.loc[
        out[
            "has_suggestive_signal"
        ].fillna(
            False
        ),
        "regional_signal_class",
    ] = "SUGGESTIVE"

    out.loc[
        out[
            "has_genome_wide_signal"
        ].fillna(
            False
        ),
        "regional_signal_class",
    ] = "GENOME_WIDE"

    # ------------------------------------------------------------------
    # Direct candidate-lead association class
    # ------------------------------------------------------------------

    out[
        "direct_lead_signal_class"
    ] = "LEAD_ABSENT"

    lead_present = (
        out[
            "lead_present"
        ].fillna(
            False
        )
    )

    out.loc[
        lead_present,
        "direct_lead_signal_class",
    ] = "LEAD_PRESENT_NON_SUGGESTIVE"

    out.loc[
        lead_present
        &
        out[
            "lead_p_value"
        ].lt(
            SUGGESTIVE_SIGNIFICANCE
        ),
        "direct_lead_signal_class",
    ] = "LEAD_SUGGESTIVE"

    out.loc[
        lead_present
        &
        out[
            "lead_p_value"
        ].lt(
            GENOME_WIDE_SIGNIFICANCE
        ),
        "direct_lead_signal_class",
    ] = "LEAD_GENOME_WIDE"

    # ------------------------------------------------------------------
    # Top signal identity relationship
    # ------------------------------------------------------------------

    out[
        "top_variant_is_candidate_lead"
    ] = (
        out[
            "top_variant_rsid"
        ]
        .astype(
            "string"
        )
        .str.lower()
        .eq(
            out[
                "lead_rsid"
            ]
            .astype(
                "string"
            )
            .str.lower()
        )
        .fillna(
            False
        )
    )

    return out


# ============================================================================
# Cross-study variant recurrence
# ============================================================================


def build_variant_recurrence(
    standardized: pd.DataFrame,
) -> pd.DataFrame:
    """
    Summarize recurrence of suggestive regional variants across studies.

    Only variants satisfying p < 1e-5 are included in this recurrence table.

    This is cross-study recurrence, NOT proof of independent replication.
    """

    required = {
        "study_accession",
        "lead_rsid",
        "variant_identity_key",
        "rsid",
        "variant_id",
        "chromosome",
        "base_pair_location",
        "distance_to_lead",
        "effect_allele",
        "other_allele",
        "beta",
        "standard_error",
        "effect_allele_frequency",
        "p_value",
        "is_genome_wide_significant",
        "is_suggestive_significant",
        "is_conflicting_variant_representation",
    }

    missing = (
        required
        - set(
            standardized.columns
        )
    )

    if missing:

        raise ValueError(
            "Standardized GWAS locus dataset is missing columns: "
            f"{sorted(missing)}"
        )

    significant = standardized.loc[
        standardized[
            "is_suggestive_significant"
        ].fillna(
            False
        )
    ].copy()

    if significant.empty:

        return pd.DataFrame(
            columns=[
                "lead_rsid",
                "variant_identity_key",
                "rsid",
                "variant_id",
                "chromosome",
                "base_pair_location",
                "distance_to_lead",
                "absolute_distance_to_lead",
                "studies_observed",
                "study_count",
                "minimum_p_value",
                "maximum_p_value",
                "genome_wide_in_any_study",
                "effect_direction_positive_studies",
                "effect_direction_negative_studies",
                "effect_direction_consistent",
                "conflicting_source_representation_present",
            ]
        )

    records: list[
        dict[str, Any]
    ] = []

    for (
        lead_rsid,
        variant_identity,
    ), group in significant.groupby(
        [
            "lead_rsid",
            "variant_identity_key",
        ],
        dropna=False,
        sort=True,
    ):

        if pd.isna(
            variant_identity
        ):
            continue

        p_values = pd.to_numeric(
            group[
                "p_value"
            ],
            errors="coerce",
        ).dropna()

        beta_values = pd.to_numeric(
            group[
                "beta"
            ],
            errors="coerce",
        ).dropna()

        positive = int(
            beta_values.gt(
                0
            ).sum()
        )

        negative = int(
            beta_values.lt(
                0
            ).sum()
        )

        nonzero_direction_count = (
            positive
            + negative
        )

        direction_consistent = (
            nonzero_direction_count
            > 0
            and
            (
                positive == 0
                or negative == 0
            )
        )

        first = group.iloc[
            0
        ]

        distance = _int_or_none(
            first[
                "distance_to_lead"
            ]
        )

        study_accessions = sorted(
            group[
                "study_accession"
            ]
            .astype(
                str
            )
            .unique()
            .tolist()
        )

        records.append(
            {
                "lead_rsid":
                    str(
                        lead_rsid
                    ),

                "variant_identity_key":
                    str(
                        variant_identity
                    ),

                "rsid":
                    (
                        None
                        if pd.isna(
                            first[
                                "rsid"
                            ]
                        )
                        else str(
                            first[
                                "rsid"
                            ]
                        )
                    ),

                "variant_id":
                    (
                        None
                        if pd.isna(
                            first[
                                "variant_id"
                            ]
                        )
                        else str(
                            first[
                                "variant_id"
                            ]
                        )
                    ),

                "chromosome":
                    (
                        None
                        if pd.isna(
                            first[
                                "chromosome"
                            ]
                        )
                        else str(
                            first[
                                "chromosome"
                            ]
                        )
                    ),

                "base_pair_location":
                    _int_or_none(
                        first[
                            "base_pair_location"
                        ]
                    ),

                "distance_to_lead":
                    distance,

                "absolute_distance_to_lead":
                    (
                        abs(
                            distance
                        )
                        if distance is not None
                        else None
                    ),

                "studies_observed":
                    "|".join(
                        study_accessions
                    ),

                "study_count":
                    int(
                        len(
                            study_accessions
                        )
                    ),

                "minimum_p_value":
                    (
                        float(
                            p_values.min()
                        )
                        if not p_values.empty
                        else None
                    ),

                "maximum_p_value":
                    (
                        float(
                            p_values.max()
                        )
                        if not p_values.empty
                        else None
                    ),

                "genome_wide_in_any_study":
                    bool(
                        group[
                            "is_genome_wide_significant"
                        ]
                        .fillna(
                            False
                        )
                        .any()
                    ),

                "effect_direction_positive_studies":
                    positive,

                "effect_direction_negative_studies":
                    negative,

                "effect_direction_consistent":
                    bool(
                        direction_consistent
                    ),

                "conflicting_source_representation_present":
                    bool(
                        group[
                            "is_conflicting_variant_representation"
                        ]
                        .fillna(
                            False
                        )
                        .any()
                    ),
            }
        )

    recurrence = pd.DataFrame(
        records
    )

    if recurrence.empty:
        return recurrence

    return recurrence.sort_values(
        [
            "lead_rsid",
            "study_count",
            "minimum_p_value",
        ],
        ascending=[
            True,
            False,
            True,
        ],
    ).reset_index(
        drop=True
    )


# ============================================================================
# Candidate lead synthesis
# ============================================================================


def build_lead_synthesis(
    locus_evidence: pd.DataFrame,
    variant_recurrence: pd.DataFrame,
) -> pd.DataFrame:
    """Create one cross-study synthesis record per candidate lead."""

    records: list[
        dict[str, Any]
    ] = []

    for lead_rsid, group in locus_evidence.groupby(
        "lead_rsid",
        sort=True,
    ):

        minimum_p_values = pd.to_numeric(
            group[
                "minimum_p_value"
            ],
            errors="coerce",
        ).dropna()

        lead_p_values = pd.to_numeric(
            group[
                "lead_p_value"
            ],
            errors="coerce",
        ).dropna()

        top_distance_values = pd.to_numeric(
            group[
                "top_variant_absolute_distance_to_lead"
            ],
            errors="coerce",
        ).dropna()

        top_row = None

        if not minimum_p_values.empty:

            top_index = pd.to_numeric(
                group[
                    "minimum_p_value"
                ],
                errors="coerce",
            ).idxmin()

            top_row = locus_evidence.loc[
                top_index
            ]

        recurrence = variant_recurrence.loc[
            variant_recurrence[
                "lead_rsid"
            ].eq(
                lead_rsid
            )
        ]

        recurrent = recurrence.loc[
            recurrence[
                "study_count"
            ].ge(
                2
            )
        ]

        maximum_variant_study_recurrence = (
            int(
                recurrence[
                    "study_count"
                ].max()
            )
            if not recurrence.empty
            else 0
        )

        studies_with_regional_signal = int(
            group[
                "has_suggestive_signal"
            ]
            .fillna(
                False
            )
            .sum()
        )

        studies_with_genome_wide_signal = int(
            group[
                "has_genome_wide_signal"
            ]
            .fillna(
                False
            )
            .sum()
        )

        studies_with_direct_lead = int(
            group[
                "lead_present"
            ]
            .fillna(
                False
            )
            .sum()
        )

        studies_with_suggestive_direct_lead = int(
            (
                pd.to_numeric(
                    group[
                        "lead_p_value"
                    ],
                    errors="coerce",
                )
                <
                SUGGESTIVE_SIGNIFICANCE
            )
            .fillna(
                False
            )
            .sum()
        )

        # --------------------------------------------------------------
        # Descriptive evidence tier
        #
        # Not a causal ranking.
        # --------------------------------------------------------------

        if studies_with_genome_wide_signal >= 1:

            evidence_tier = (
                "REGIONAL_GENOME_WIDE"
            )

        elif studies_with_regional_signal >= 2:

            evidence_tier = (
                "RECURRENT_SUGGESTIVE"
            )

        elif studies_with_regional_signal == 1:

            evidence_tier = (
                "SINGLE_STUDY_SUGGESTIVE"
            )

        else:

            evidence_tier = (
                "NO_SUGGESTIVE_REGIONAL_SIGNAL"
            )

        # --------------------------------------------------------------
        # Direct-vs-regional interpretation
        # --------------------------------------------------------------

        if (
            studies_with_regional_signal
            > 0
            and
            studies_with_suggestive_direct_lead
            == 0
        ):

            signal_architecture = (
                "REGIONAL_SIGNAL_WITHOUT_DIRECT_LEAD_ASSOCIATION"
            )

        elif studies_with_suggestive_direct_lead > 0:

            signal_architecture = (
                "DIRECT_LEAD_ASSOCIATION_PRESENT"
            )

        else:

            signal_architecture = (
                "NO_SUGGESTIVE_DISEASE_SIGNAL"
            )

        records.append(
            {
                "lead_rsid":
                    str(
                        lead_rsid
                    ),

                "studies_with_locus":
                    int(
                        len(
                            group
                        )
                    ),

                "studies_with_direct_lead":
                    studies_with_direct_lead,

                "studies_with_suggestive_direct_lead":
                    studies_with_suggestive_direct_lead,

                "studies_with_suggestive_regional_signal":
                    studies_with_regional_signal,

                "studies_with_genome_wide_regional_signal":
                    studies_with_genome_wide_signal,

                "best_regional_p_value":
                    (
                        float(
                            minimum_p_values.min()
                        )
                        if not minimum_p_values.empty
                        else None
                    ),

                "best_direct_lead_p_value":
                    (
                        float(
                            lead_p_values.min()
                        )
                        if not lead_p_values.empty
                        else None
                    ),

                "best_signal_study":
                    (
                        str(
                            top_row[
                                "study_accession"
                            ]
                        )
                        if top_row is not None
                        else None
                    ),

                "best_signal_variant_rsid":
                    (
                        None
                        if (
                            top_row is None
                            or pd.isna(
                                top_row[
                                    "top_variant_rsid"
                                ]
                            )
                        )
                        else str(
                            top_row[
                                "top_variant_rsid"
                            ]
                        )
                    ),

                "best_signal_variant_id":
                    (
                        None
                        if (
                            top_row is None
                            or pd.isna(
                                top_row[
                                    "top_variant_id"
                                ]
                            )
                        )
                        else str(
                            top_row[
                                "top_variant_id"
                            ]
                        )
                    ),

                "best_signal_distance_to_lead":
                    (
                        None
                        if top_row is None
                        else _int_or_none(
                            top_row[
                                "top_variant_distance_to_lead"
                            ]
                        )
                    ),

                "nearest_top_signal_distance":
                    (
                        int(
                            top_distance_values.min()
                        )
                        if not top_distance_values.empty
                        else None
                    ),

                "suggestive_variants_observed":
                    int(
                        group[
                            "suggestive_significant_variants"
                        ].sum()
                    ),

                "suggestive_only_variants_observed":
                    int(
                        group[
                            "suggestive_only_variants"
                        ].sum()
                    ),

                "genome_wide_variants_observed":
                    int(
                        group[
                            "genome_wide_significant_variants"
                        ].sum()
                    ),

                "recurrent_suggestive_variant_count":
                    int(
                        len(
                            recurrent
                        )
                    ),

                "maximum_variant_study_recurrence":
                    maximum_variant_study_recurrence,

                "regional_evidence_tier":
                    evidence_tier,

                "signal_architecture":
                    signal_architecture,

                "ld_analysis_required":
                    bool(
                        studies_with_regional_signal
                        > 0
                        and
                        studies_with_suggestive_direct_lead
                        == 0
                    ),

                "colocalization_not_assessed":
                    True,
            }
        )

    synthesis = pd.DataFrame(
        records
    )

    if synthesis.empty:
        return synthesis

    # ------------------------------------------------------------------
    # Descriptive priority rank
    #
    # Rank:
    #   1. genome-wide regional evidence
    #   2. number of studies with p < 1e-5
    #   3. best regional p-value
    #
    # Does not represent causal probability.
    # ------------------------------------------------------------------

    synthesis = synthesis.sort_values(
        [
            "studies_with_genome_wide_regional_signal",
            "studies_with_suggestive_regional_signal",
            "best_regional_p_value",
        ],
        ascending=[
            False,
            False,
            True,
        ],
    ).reset_index(
        drop=True
    )

    synthesis[
        "descriptive_evidence_rank"
    ] = (
        synthesis.index
        + 1
    )

    return synthesis


# ============================================================================
# Public synthesis function
# ============================================================================


def synthesize_cross_study_signal(
    *,
    standardized: pd.DataFrame,
    disease_signal: pd.DataFrame,
) -> CrossStudySynthesisResult:
    """Run all M5.3C.3E synthesis components."""

    locus_evidence = build_locus_evidence(
        disease_signal
    )

    variant_recurrence = build_variant_recurrence(
        standardized
    )

    lead_synthesis = build_lead_synthesis(
        locus_evidence,
        variant_recurrence,
    )

    return CrossStudySynthesisResult(
        locus_evidence=locus_evidence,
        lead_synthesis=lead_synthesis,
        variant_recurrence=variant_recurrence,
    )