"""
PCa-tRFQTL Research Pipeline
=============================

File:
    src/pcatrfqtl/analysis/m7/runners/audit_external_trf_positional_flanking.py

Description:
    Runner for M7.4C.2B External tRF Positional and Flanking Audit.

    Existing GSE80400 FASTQ files generated by M7.4C.2 are reused.
    No additional SRA download is performed.

Author:
    I Putu Indra Arsana

Project:
    Integrative Analysis of Prostate Cancer Risk Variants,
    tRNA-Derived Fragment QTLs, and Transcript Isoform Regulation

License:
    MIT
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pandas as pd
import yaml

from pcatrfqtl.analysis.m7.external_trf_positional_flanking_audit import (
    audit_external_trf_positional_flanking_context,
)
from pcatrfqtl.io.parquet import write_parquet
from pcatrfqtl.logging.logger import get_logger


logger = get_logger(__name__)


def _json_safe_row(
    row: pd.Series,
) -> dict[str, Any]:

    output: dict[str, Any] = {}

    for key, value in row.to_dict().items():

        if hasattr(
            value,
            "item",
        ):
            value = value.item()

        output[
            str(
                key
            )
        ] = value

    return output


def _records(
    dataframe: pd.DataFrame,
) -> list[dict[str, Any]]:

    if dataframe.empty:
        return []

    clean = dataframe.astype(
        object
    ).where(
        pd.notna(
            dataframe
        ),
        None,
    )

    return clean.to_dict(
        orient="records"
    )


class M74C2BExternalTrfPositionalFlankingRunner:
    """Execute M7.4C.2B."""

    def __init__(
        self,
        *,
        project_root: str | Path,
        config_path: str | Path,
    ) -> None:

        self.project_root = Path(
            project_root
        )

        self.config_path = Path(
            config_path
        )

    def _load_config(
        self,
    ) -> dict[str, Any]:

        with self.config_path.open(
            "r",
            encoding="utf-8",
        ) as handle:

            config = yaml.safe_load(
                handle
            )

        if config.get(
            "milestone"
        ) != "M7.4C.2B":

            raise RuntimeError(
                "Unexpected M7.4C.2B milestone."
            )

        return config

    def _validate_upstream(
        self,
        *,
        config: dict[str, Any],
    ) -> Path:

        upstream = config[
            "upstream_qc"
        ][
            "exact_sequence_counting"
        ]

        path = (
            self.project_root
            /
            upstream[
                "relative_path"
            ]
        )

        if not path.exists():

            raise FileNotFoundError(
                f"Locked M7.4C.2 QC not found: {path}"
            )

        with path.open(
            "r",
            encoding="utf-8",
        ) as handle:

            payload = json.load(
                handle
            )

        if payload.get(
            "milestone"
        ) != upstream[
            "expected_milestone"
        ]:

            raise RuntimeError(
                "Unexpected upstream milestone."
            )

        summary = payload.get(
            "summary",
            {},
        )

        if summary.get(
            "execution_mode"
        ) != upstream[
            "expected_execution_mode"
        ]:

            raise RuntimeError(
                "M7.4C.2 upstream is not full mode."
            )

        if summary.get(
            "overall_status"
        ) != upstream[
            "expected_overall_status"
        ]:

            raise RuntimeError(
                "Unexpected M7.4C.2 upstream status."
            )

        return path

    def _resolve_fastqs(
        self,
        *,
        config: dict[str, Any],
    ) -> dict[str, Path]:

        directory = (
            self.project_root
            /
            config[
                "fastq"
            ][
                "directory"
            ]
        )

        template = config[
            "fastq"
        ][
            "filename_template"
        ]

        result: dict[
            str,
            Path
        ] = {}

        for accession in config[
            "runs"
        ]:

            path = (
                directory
                /
                template.format(
                    run_accession=accession
                )
            )

            if not path.exists():

                raise FileNotFoundError(
                    f"FASTQ missing for {accession}: {path}"
                )

            result[
                accession
            ] = path

        return result

    def run(
        self,
    ) -> dict[str, Any]:

        config = self._load_config()

        upstream_path = self._validate_upstream(
            config=config,
        )

        fastqs = self._resolve_fastqs(
            config=config,
        )

        logger.info(
            "M7.4C.2B auditing %d existing FASTQs.",
            len(
                fastqs
            ),
        )

        result = audit_external_trf_positional_flanking_context(
            run_fastq_paths=fastqs,
            config=config,
        )

        output_config = config[
            "outputs"
        ]

        output_directory = (
            self.project_root
            /
            output_config[
                "processed_directory"
            ]
        )

        output_directory.mkdir(
            parents=True,
            exist_ok=True,
        )

        run_summary_path = (
            output_directory
            /
            output_config[
                "run_summary_filename"
            ]
        )

        length_path = (
            output_directory
            /
            output_config[
                "length_distribution_filename"
            ]
        )

        context_path = (
            output_directory
            /
            output_config[
                "motif_context_filename"
            ]
        )

        context_aggregate_path = (
            output_directory
            /
            output_config[
                "motif_context_aggregate_filename"
            ]
        )

        summary_path = (
            output_directory
            /
            output_config[
                "overall_summary_filename"
            ]
        )

        write_parquet(
            result.run_summary,
            run_summary_path,
            index=False,
        )

        write_parquet(
            result.length_distribution,
            length_path,
            index=False,
        )

        write_parquet(
            result.motif_context,
            context_path,
            index=False,
        )

        write_parquet(
            result.motif_context_aggregate,
            context_aggregate_path,
            index=False,
        )

        write_parquet(
            result.summary,
            summary_path,
            index=False,
        )

        summary = _json_safe_row(
            result.summary.iloc[
                0
            ]
        )

        qc_path = (
            self.project_root
            /
            output_config[
                "qc_relative_path"
            ]
        )

        qc_path.parent.mkdir(
            parents=True,
            exist_ok=True,
        )

        report = {
            "milestone":
                "M7.4C.2B",

            "stage":
                config[
                    "stage"
                ],

            "upstream_qc":
                str(
                    upstream_path
                ),

            "candidate":
                config[
                    "candidate"
                ],

            "dataset":
                config[
                    "dataset"
                ],

            "read_length_policy":
                config[
                    "read_length_policy"
                ],

            "summary":
                summary,

            "run_summary":
                _records(
                    result.run_summary
                ),

            "top_motif_contexts":
                _records(
                    result
                    .motif_context_aggregate
                    .head(
                        50
                    )
                ),

            "scientific_policy":
                config[
                    "scientific_policy"
                ],

            "outputs": {
                "run_summary":
                    str(
                        run_summary_path
                    ),

                "length_distribution":
                    str(
                        length_path
                    ),

                "motif_context":
                    str(
                        context_path
                    ),

                "motif_context_aggregate":
                    str(
                        context_aggregate_path
                    ),

                "summary":
                    str(
                        summary_path
                    ),
            },
        }

        with qc_path.open(
            "w",
            encoding="utf-8",
        ) as handle:

            json.dump(
                report,
                handle,
                indent=2,
                ensure_ascii=False,
            )

        logger.info(
            "M7.4C.2B complete."
        )

        logger.info(
            "Reads total=%d | <15=%d | 15-35=%d | >35=%d.",
            summary[
                "total_reads"
            ],
            summary[
                "reads_lt15"
            ],
            summary[
                "reads_15_to_35"
            ],
            summary[
                "reads_gt35"
            ],
        )

        logger.info(
            "Motif-positive all=%d | <15=%d | 15-35=%d | >35=%d.",
            summary[
                "motif_positive_reads_all_lengths"
            ],
            summary[
                "motif_positive_reads_lt15"
            ],
            summary[
                "motif_positive_reads_15_to_35"
            ],
            summary[
                "motif_positive_reads_gt35"
            ],
        )

        logger.info(
            "Full-length=%d | 5prime=%d | 3prime=%d | internal=%d.",
            summary[
                "full_length_24nt_reads"
            ],
            summary[
                "five_prime_boundary_reads"
            ],
            summary[
                "three_prime_boundary_reads"
            ],
            summary[
                "internal_motif_reads"
            ],
        )

        logger.info(
            "Interpretation=%s.",
            summary[
                "interpretation_status"
            ],
        )

        logger.info(
            "Next=%s.",
            summary[
                "next_stage"
            ],
        )

        return report