"""
PCa-tRFQTL Research Pipeline
=============================

File:
    src/pcatrfqtl/analysis/m7/candidate_fragment_interpretation.py

Description:
    Core logic for M7.4C.2C Candidate Fragment Interpretation.

    This module interprets exact candidate-sequence evidence using positional
    and flanking-context artifacts generated by M7.4C.2B.

    It does not re-read FASTQ files and does not perform new sequence
    quantification.

Author:
    I Putu Indra Arsana

Project:
    Integrative Analysis of Prostate Cancer Risk Variants,
    tRNA-Derived Fragment QTLs, and Transcript Isoform Regulation

License:
    MIT
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

import pandas as pd


@dataclass(frozen=True)
class CandidateFragmentInterpretationResult:
    """Container for M7.4C.2C output tables."""

    flank_architecture: pd.DataFrame
    interpretation: pd.DataFrame
    summary: pd.DataFrame


def build_flank_architecture(
    *,
    motif_context_aggregate: pd.DataFrame,
    config: dict[str, Any],
) -> pd.DataFrame:
    """Summarize recurrent candidate positional/flanking contexts."""

    if motif_context_aggregate.empty:

        return pd.DataFrame(
            columns=[
                "rank",
                "read_length_nt",
                "candidate_start_0based",
                "candidate_end_0based_exclusive",
                "boundary_class",
                "left_flank_sequence",
                "right_flank_sequence",
                "occurrence_count",
                "runs_observed",
                "occurrence_fraction",
                "recurrent_context",
            ]
        )

    required = {
        "read_length_nt",
        "candidate_start_0based",
        "candidate_end_0based_exclusive",
        "boundary_class",
        "left_flank_sequence",
        "right_flank_sequence",
        "occurrence_count",
        "runs_observed",
    }

    missing = required - set(
        motif_context_aggregate.columns
    )

    if missing:

        raise RuntimeError(
            "M7.4C.2C motif-context aggregate missing columns: "
            f"{sorted(missing)}"
        )

    result = motif_context_aggregate.copy()

    total_occurrences = int(
        result[
            "occurrence_count"
        ].sum()
    )

    if total_occurrences <= 0:

        raise RuntimeError(
            "M7.4C.2C received zero motif occurrences."
        )

    result[
        "occurrence_fraction"
    ] = (
        result[
            "occurrence_count"
        ]
        /
        total_occurrences
    )

    min_runs = int(
        config[
            "flank_analysis"
        ][
            "recurrent_flank_min_runs"
        ]
    )

    min_occurrences = int(
        config[
            "flank_analysis"
        ][
            "recurrent_flank_min_occurrences"
        ]
    )

    result[
        "recurrent_context"
    ] = (
        (
            result[
                "runs_observed"
            ]
            >=
            min_runs
        )
        &
        (
            result[
                "occurrence_count"
            ]
            >=
            min_occurrences
        )
    )

    result = result.sort_values(
        [
            "occurrence_count",
            "runs_observed",
            "read_length_nt",
        ],
        ascending=[
            False,
            False,
            True,
        ],
        kind="stable",
    ).reset_index(
        drop=True
    )

    result.insert(
        0,
        "rank",
        range(
            1,
            len(result) + 1,
        ),
    )

    return result


def build_interpretation(
    *,
    run_summary: pd.DataFrame,
    flank_architecture: pd.DataFrame,
    config: dict[str, Any],
) -> pd.DataFrame:
    """Classify external sequence evidence into a fragment interpretation."""

    if run_summary.empty:

        raise RuntimeError(
            "M7.4C.2C run summary is empty."
        )

    positive_reads = int(
        run_summary[
            "motif_positive_reads"
        ].sum()
    )

    positive_runs = int(
        (
            run_summary[
                "motif_positive_reads"
            ]
            >
            0
        ).sum()
    )

    full_length = int(
        run_summary[
            "full_length_24nt_reads"
        ].sum()
    )

    five_prime = int(
        run_summary[
            "five_prime_boundary_reads"
        ].sum()
    )

    three_prime = int(
        run_summary[
            "three_prime_boundary_reads"
        ].sum()
    )

    internal = int(
        run_summary[
            "internal_motif_reads"
        ].sum()
    )

    multiple = int(
        run_summary[
            "multiple_occurrence_reads"
        ].sum()
    )

    if positive_reads > 0:

        full_fraction = (
            full_length
            /
            positive_reads
        )

        five_prime_fraction = (
            five_prime
            /
            positive_reads
        )

        three_prime_fraction = (
            three_prime
            /
            positive_reads
        )

        internal_fraction = (
            internal
            /
            positive_reads
        )

    else:

        full_fraction = 0.0
        five_prime_fraction = 0.0
        three_prime_fraction = 0.0
        internal_fraction = 0.0

    rules = config[
        "interpretation_rules"
    ]

    classes = config[
        "evidence_classes"
    ]

    minimum_positive = int(
        rules[
            "minimum_total_positive_reads"
        ]
    )

    minimum_positive_runs = int(
        rules[
            "minimum_runs_with_positive_reads"
        ]
    )

    direct_fraction = float(
        rules[
            "direct_fragment"
        ][
            "minimum_full_length_fraction"
        ]
    )

    five_prime_threshold = float(
        rules[
            "five_prime_boundary"
        ][
            "minimum_boundary_fraction"
        ]
    )

    three_prime_threshold = float(
        rules[
            "three_prime_boundary"
        ][
            "minimum_boundary_fraction"
        ]
    )

    internal_threshold = float(
        rules[
            "internal_motif"
        ][
            "minimum_internal_fraction"
        ]
    )

    sufficient = bool(
        positive_reads >= minimum_positive
        and
        positive_runs >= minimum_positive_runs
    )

    if not sufficient:

        evidence_class = classes[
            "insufficient"
        ]

    elif (
        full_length > 0
        and
        full_fraction >= direct_fraction
    ):

        evidence_class = classes[
            "direct_fragment"
        ]

    elif (
        five_prime_fraction
        >=
        five_prime_threshold
        and
        full_length == 0
    ):

        evidence_class = classes[
            "five_prime_longer_context"
        ]

    elif (
        three_prime_fraction
        >=
        three_prime_threshold
        and
        full_length == 0
    ):

        evidence_class = classes[
            "three_prime_longer_context"
        ]

    elif (
        (
            five_prime > 0
            or
            three_prime > 0
        )
        and
        full_length == 0
    ):

        evidence_class = classes[
            "mixed_boundary"
        ]

    elif (
        internal_fraction
        >=
        internal_threshold
    ):

        evidence_class = classes[
            "internal_motif"
        ]

    else:

        evidence_class = classes[
            "insufficient"
        ]

    unique_contexts = int(
        len(
            flank_architecture
        )
    )

    recurrent_contexts = int(
        flank_architecture[
            "recurrent_context"
        ]
        .fillna(
            False
        )
        .astype(
            bool
        )
        .sum()
    ) if not flank_architecture.empty else 0

    if not flank_architecture.empty:

        dominant = flank_architecture.iloc[
            0
        ]

        dominant_context_count = int(
            dominant[
                "occurrence_count"
            ]
        )

        dominant_context_fraction = float(
            dominant[
                "occurrence_fraction"
            ]
        )

        dominant_context_runs = int(
            dominant[
                "runs_observed"
            ]
        )

        dominant_read_length = int(
            dominant[
                "read_length_nt"
            ]
        )

        dominant_start = int(
            dominant[
                "candidate_start_0based"
            ]
        )

        dominant_boundary_class = str(
            dominant[
                "boundary_class"
            ]
        )

        dominant_left_flank = str(
            dominant[
                "left_flank_sequence"
            ]
        )

        dominant_right_flank = str(
            dominant[
                "right_flank_sequence"
            ]
        )

    else:

        dominant_context_count = 0
        dominant_context_fraction = 0.0
        dominant_context_runs = 0
        dominant_read_length = None
        dominant_start = None
        dominant_boundary_class = None
        dominant_left_flank = None
        dominant_right_flank = None

    return pd.DataFrame(
        [
            {
                "candidate_trf":
                    config[
                        "candidate"
                    ][
                        "trf_id"
                    ],

                "candidate_sequence":
                    config[
                        "candidate"
                    ][
                        "exact_sequence"
                    ],

                "candidate_length_nt":
                    int(
                        config[
                            "candidate"
                        ][
                            "sequence_length_nt"
                        ]
                    ),

                "positive_reads":
                    positive_reads,

                "positive_runs":
                    positive_runs,

                "full_length_24nt_reads":
                    full_length,

                "five_prime_boundary_reads":
                    five_prime,

                "three_prime_boundary_reads":
                    three_prime,

                "internal_motif_reads":
                    internal,

                "multiple_occurrence_reads":
                    multiple,

                "full_length_fraction":
                    float(
                        full_fraction
                    ),

                "five_prime_boundary_fraction":
                    float(
                        five_prime_fraction
                    ),

                "three_prime_boundary_fraction":
                    float(
                        three_prime_fraction
                    ),

                "internal_motif_fraction":
                    float(
                        internal_fraction
                    ),

                "unique_flanking_contexts":
                    unique_contexts,

                "recurrent_flanking_contexts":
                    recurrent_contexts,

                "dominant_context_occurrences":
                    dominant_context_count,

                "dominant_context_fraction":
                    dominant_context_fraction,

                "dominant_context_runs":
                    dominant_context_runs,

                "dominant_read_length_nt":
                    dominant_read_length,

                "dominant_candidate_start_0based":
                    dominant_start,

                "dominant_boundary_class":
                    dominant_boundary_class,

                "dominant_left_flank":
                    dominant_left_flank,

                "dominant_right_flank":
                    dominant_right_flank,

                "direct_24nt_fragment_supported":
                    bool(
                        evidence_class
                        ==
                        classes[
                            "direct_fragment"
                        ]
                    ),

                "boundary_compatible_support":
                    bool(
                        five_prime > 0
                        or
                        three_prime > 0
                    ),

                "longer_fragment_context_present":
                    bool(
                        (
                            five_prime > 0
                            or
                            three_prime > 0
                            or
                            internal > 0
                        )
                        and
                        full_length == 0
                    ),

                "evidence_class":
                    evidence_class,
            }
        ]
    )


def build_summary(
    *,
    interpretation: pd.DataFrame,
    config: dict[str, Any],
) -> pd.DataFrame:
    """Build one-row M7.4C.2C summary."""

    if len(
        interpretation
    ) != 1:

        raise RuntimeError(
            "M7.4C.2C interpretation must contain one row."
        )

    row = interpretation.iloc[
        0
    ]

    insufficient_class = (
        config[
            "evidence_classes"
        ][
            "insufficient"
        ]
    )

    complete = bool(
        row[
            "evidence_class"
        ]
        !=
        insufficient_class
    )

    overall_status = (
        config[
            "statuses"
        ][
            "complete"
        ]
        if complete
        else
        config[
            "statuses"
        ][
            "insufficient"
        ]
    )

    next_stage = (
        config[
            "next_stage"
        ][
            "if_complete"
        ]
        if complete
        else
        config[
            "next_stage"
        ][
            "if_insufficient"
        ]
    )

    return pd.DataFrame(
        [
            {
                "milestone":
                    "M7.4C.2C",

                "dataset_key":
                    config[
                        "dataset"
                    ][
                        "dataset_key"
                    ],

                "candidate_trf":
                    row[
                        "candidate_trf"
                    ],

                "positive_reads":
                    int(
                        row[
                            "positive_reads"
                        ]
                    ),

                "positive_runs":
                    int(
                        row[
                            "positive_runs"
                        ]
                    ),

                "full_length_24nt_reads":
                    int(
                        row[
                            "full_length_24nt_reads"
                        ]
                    ),

                "five_prime_boundary_reads":
                    int(
                        row[
                            "five_prime_boundary_reads"
                        ]
                    ),

                "three_prime_boundary_reads":
                    int(
                        row[
                            "three_prime_boundary_reads"
                        ]
                    ),

                "internal_motif_reads":
                    int(
                        row[
                            "internal_motif_reads"
                        ]
                    ),

                "five_prime_boundary_fraction":
                    float(
                        row[
                            "five_prime_boundary_fraction"
                        ]
                    ),

                "dominant_context_fraction":
                    float(
                        row[
                            "dominant_context_fraction"
                        ]
                    ),

                "dominant_context_runs":
                    int(
                        row[
                            "dominant_context_runs"
                        ]
                    ),

                "direct_24nt_fragment_supported":
                    bool(
                        row[
                            "direct_24nt_fragment_supported"
                        ]
                    ),

                "longer_fragment_context_present":
                    bool(
                        row[
                            "longer_fragment_context_present"
                        ]
                    ),

                "evidence_class":
                    row[
                        "evidence_class"
                    ],

                "parent_trna_inference_performed":
                    False,

                "genomic_origin_inference_performed":
                    False,

                "adapter_origin_assumed":
                    False,

                "clinical_association_performed":
                    False,

                "causal_inference_performed":
                    False,

                "overall_status":
                    overall_status,

                "next_stage":
                    next_stage,
            }
        ]
    )


def interpret_candidate_fragment(
    *,
    run_summary: pd.DataFrame,
    motif_context_aggregate: pd.DataFrame,
    config: dict[str, Any],
) -> CandidateFragmentInterpretationResult:
    """Execute M7.4C.2C."""

    flank_architecture = build_flank_architecture(
        motif_context_aggregate=motif_context_aggregate,
        config=config,
    )

    interpretation = build_interpretation(
        run_summary=run_summary,
        flank_architecture=flank_architecture,
        config=config,
    )

    summary = build_summary(
        interpretation=interpretation,
        config=config,
    )

    return CandidateFragmentInterpretationResult(
        flank_architecture=flank_architecture,
        interpretation=interpretation,
        summary=summary,
    )