"""
PCa-tRFQTL Research Pipeline
=============================

File:
    src/pcatrfqtl/analysis/m3/gwas.py

Description:
    Core scientific logic for M3.1 prostate-cancer GWAS selection.

    M3.1 selects harmonized GWAS Catalog association records whose
    disease context has been resolved to the project's primary disease:

        prostate cancer

    The stage preserves all prostate-cancer association rows and adds
    explicit eligibility metadata for the later M3.3 direct rsID
    overlap with Cancer-tRFQTL.

    M3.1 intentionally does not:

        - join GWAS with tRF-QTL
        - deduplicate GWAS associations
        - collapse multiple studies per variant
        - perform genome liftover
        - perform coordinate-based matching
        - impose a new GWAS significance threshold
        - rank candidate variants

Author:
    I Putu Indra Arsana

Project:
    Integrative Analysis of Prostate Cancer Risk Variants,
    tRNA-Derived Fragment QTLs, and Transcript Isoform Regulation

License:
    MIT
"""

from __future__ import annotations

import pandas as pd


class ProstateGWASSelector:
    """
    Select prostate-cancer GWAS associations from harmonized data.

    Direct-overlap eligibility requires a canonical single rsID because
    M3.3 will initially use rsID identity rather than genomic coordinate
    matching.
    """

    PRIMARY_DISEASE_ID = "prostate_cancer"

    REQUIRED_COLUMNS = {
        "harm_is_primary_disease",
        "harm_disease_id",
        "harm_variant_rsid",
        "harm_variant_rsid_usable",
        "harm_variant_identity_key",
    }

    @classmethod
    def validate_schema(
        cls,
        dataframe: pd.DataFrame,
    ) -> None:
        """Require harmonized GWAS fields needed by M3.1."""

        missing = (
            cls.REQUIRED_COLUMNS
            - set(
                dataframe.columns
            )
        )

        if missing:
            raise ValueError(
                "Harmonized GWAS input is missing required "
                f"M3.1 columns: {sorted(missing)}"
            )

    @classmethod
    def select_primary_disease(
        cls,
        dataframe: pd.DataFrame,
    ) -> pd.DataFrame:
        """
        Select harmonized prostate-cancer GWAS association rows.

        Selection is based on the disease identity generated by the
        harmonization layer rather than text matching raw GWAS labels.
        """

        cls.validate_schema(
            dataframe
        )

        mask = (
            dataframe[
                "harm_is_primary_disease"
            ]
            .fillna(False)
            .eq(True)
            & dataframe[
                "harm_disease_id"
            ]
            .eq(
                cls.PRIMARY_DISEASE_ID
            )
        )

        result = (
            dataframe.loc[
                mask
            ]
            .copy()
        )

        return result

    @staticmethod
    def add_overlap_eligibility(
        dataframe: pd.DataFrame,
    ) -> pd.DataFrame:
        """
        Annotate whether each association can participate in M3.3.

        Initial M3 direct overlap requires one canonical rsID.

        Records with complex/non-rsID GWAS descriptors remain in the
        M3.1 dataset but are marked as ineligible for direct rsID
        overlap.
        """

        result = (
            dataframe.copy()
        )

        result[
            "m3_direct_overlap_eligible"
        ] = (
            result[
                "harm_variant_rsid_usable"
            ]
            .fillna(False)
            .eq(True)
            & result[
                "harm_variant_rsid"
            ]
            .notna()
        )

        result[
            "m3_selection_reason"
        ] = (
            "harmonized_primary_disease"
        )

        return result

    @classmethod
    def prepare(
        cls,
        dataframe: pd.DataFrame,
    ) -> pd.DataFrame:
        """
        Produce an M3.1 prostate-cancer GWAS subset.

        Row order is preserved relative to the harmonized source.
        """

        selected = (
            cls.select_primary_disease(
                dataframe
            )
        )

        selected = (
            cls.add_overlap_eligibility(
                selected
            )
        )

        return selected